### PR TITLE
V3 response request models

### PR DESCRIPTION
**Pull request by Stormsys**
Adding this for visibility for #78 - work in progress

### CODE REVIEW

**Comment by Jetski5822** [comment]
Sure you were meant to merge this? It has DNMY on it?

**Comment by hjaltethor** [comment]
We removed the DNMY before merging. It's an alpha release that we'll test internally and then promote or fix if we find any issues.

**Comment by Jetski5822** [comment]
Groovy.. however, an Alpha release? Didn't we do a beta of v3 already? What version will be the next?

**Comment by hjaltethor** [comment]
This release contains a few breaking changes from v3, so we thought it'd be best to differentiate them. Once we've tested it in a production-like environment, we can promote it to beta.

**Comment by Jetski5822** [comment]
Breaking changes in a beta is fine. Maybe let's go with a 3.5-alpha.... something

**Pull request merged**
