### PR TITLE
add ability to search using a string rather than using the builder.

### PR DESCRIPTION
**Pull request by jonathanstowell**

### CODE REVIEW

**Comment by jonathanstowell** [comment]
@corneliuskopp the builder will make it difficult for us to provide a generic search endpoint for the Operation Support Service. 

We would need to have specific routes to cover the searches consumers are performing which becomes a maintenance nightmare when they want to search by something we don't have. Otherwise we need to implement something that parses a string and then builds up the QueryBuilder .

Seemed easier to have a way of directly calling search without using the builder. That way we can provide a JE internal client which has the same builder process as here, but pumps the query output to our service.

**Comment by jonathanstowell** [comment]
I'm confused. The internal client will need to hit our Operations Support API via HTTP so will need to pass the search query term for us to proxy it on to Zendesk? 

If we receive something like "type:user email:some@email.com tags:owner" we can stream that directly to Zendesk allowing consumers to build up searches for anything, like they're able to now. At the moment if we receive something like that now, we're going to have to parse it and use the builder to generate the same string output.

Unless we even make searching specific which feels like it would cause roadblocks in the future with consumers waiting on us to implement routes for them.

**Comment by corneliuskopp** [comment]
I'm afraid you are mistaken; check out the linked-to extension that makes generating a generic query easier, and you can DIY build the query as is. There's a reason why I linked this.

Otherwise, please elaborate -- keeping this capability in mind -- why we have to parse a consumer's search string? I may be missing something in there.

**Comment by jonathanstowell** [comment]
We might want to rename / add another extension for this. WithWord is slightly confusing for my usage. I imagine that was added to use the search where you provide a single word and it will search across everything. My usage is more providing the whole QueryString so perhaps a WithQueryString extension might be clearer. Could also be useful getting some documentation with examples around this. Then I can stop bothering you :-)

**Pull request closed without merging**
