### PR TITLE
Remove internal keyword from responses and standardize request and response names

### PR DESCRIPTION
**Pull request by hjaltethor**
Internal responses made unit testing difficult for consumers of the client, as it made mocking responses from the client much harder than it needed to be.

When making this change I noticed a lot of inconsistency in the naming of requests and responses, and have attempted to standardize them.

### CODE REVIEW

**Comment by Jetski5822** [comment]
Hmmm on second thought, they are internal for a reason. Only the server can set them.... consumers of the client should mock api responses..

How does that work at the moment?

**Comment by hjaltethor** [comment]
When integrating the alpha version of the client, I found that writing good unit tests became very difficult as I couldn't use any of the responses on a mocked version of the API, as they were internal.

Given a response from the client with X values
When I map that to my own data models
Then everything was mapped correctly

If I wanted to write the above test for my mapper, I need to be able to create different response objects from the API.

If we're afraid of someone reusing the response models, I don't believe that's an issue, as you can't use them in the resources in the client.

**Comment by Jetski5822** [comment]
Right... I think I understand what you are trying to do, and yeah - having them as internal does suck in that instance

Ah - hang on, so we have separated Response and Request object havent we! - okay cool.

Merge it.

**Comment by Stormsys** [comment]
@hjaltethor Merge conflicts, il get this through once you fix them :)

**Pull request closed without merging**
