### PR TITLE
Release as nonalpha

### PR DESCRIPTION
**Pull request by corneliuskopp**
It has been in alpha status since mid-2017. Hjalte suggested that it is maybe time to make this an official release, and I would agree. Otherwise our shiny new improvements might be hard to discover for JustEat-ers and outside.

(I hope that those two changes is all that is required to get a "production" build.)

### CODE REVIEW

**Comment by gareththackeray-je** [comment]
From my experience I'd be pretty surprised if this works well enough to put our name on it and call it a production-ready release.  The features I needed had clearly never been run and didn't work at all.  Perhaps this is different now but I doubt anyone has exercised the entire thing.  @hjaltethor ?

**Comment by corneliuskopp** [comment]
It's been in production use for about a year here with us; I can't vouch for "exercise the entire thing", that is true.
Last time I made a change to the ZD client, there was talk about "we should make this a real release", so I thought I trigger a discussion about it.

**Comment by gareththackeray-je** [comment]
I would say that as it's a "justeat" release we should be more sure about it working than hoping for the best.  I doubt anyone's going to do that off their own backs so either we leave as pre-release or bring it internally, IMO.

**Comment by corneliuskopp** [comment]
@gareththackeray-je That's why I gave you more information than "hoping for the best". I also don't think closed-sourcing is necessarily the right step forward.

@hjaltethor does that mean you'd prefer it to stay in prerelease?

**Comment by gareththackeray-je** [comment]
The bits that work, work.  But I doubt we have a handle on what is as-yet-untested.

**Comment by Jetski5822** [comment]
I agree with @hjaltethor and @corneliuskopp - the package has been out there for some time, and people are using it in production.

From the PRs I have seen come through, people are fixing bugs off their own back, so close sourcing a project just makes all that community love go away.

@gareththackeray-je what bugs did you run in too? and did you log any issues around them?

**Comment by gareththackeray-je** [comment]
https://github.com/justeat/ZendeskApiClient/pull/101
https://github.com/justeat/ZendeskApiClient/pull/102

The point is that the SDK covers the entire ZD api but we only use a subset.  When I made those fixes above it was quite obvious that it'd never been run against the actual ZD API.  So I would expect a good chance of similar errors for endpoints that we never use.

**Comment by gareththackeray-je** [comment]
It just seems a bit shonky to declare it ready for use when we don't actually know, in general.

**Comment by Jetski5822** [comment]
The SDK covers alot, but not all of the ZD API. The only way to get true adoption is to get people using it, people tend to steer away from alpha releases.

Just do a release, then do point releases afterwards...

**Comment by corneliuskopp** [comment]
I completely understand Gareth's concerns; I wouldn't throw it out there either if it was new and untested. I created this PR mostly off conversations I had with Hjalte; I wasn't the first person who ran into not seeing the new and fixed version of the ZD client, because I don't generally look for alphas either – and duplicated some amount of work before the alpha version got pointed out to me.

Now, that absolutely doesn't excuse blindly releasing code. That's not what I am trying to say. The reason I mention this anecdote is indeed to show there are downsides of keeping this in alpha. Especially when it is already running in production. (And that I didn't do this on a whim. :))

Maybe we should take one of Gareth's earlier remarks to heart and have a look at what parts of our client are available but simply not enough exercised? Look for a baseline confidence level where we are happy to show this to the world at large?

(Though I appreciate @Jetski5822 's offer to do some adoption, testing and issue-raising/PR-making. 😇 )

**Comment by slang25** [comment]
Given we are over a year on, what are the feelings for a point release now?

I see the numbers are looking good in terms of downloads on the alphas, and today the latest stable version isn't compatible with .NET Core, which is going to cause consumers confusion (literally just happened in my team).

**Comment by slang25** [comment]
@jonathanstowell @LoadData @corneliuskopp Do you have thoughts on this?

**Comment by gareththackeray** [comment]
Hi Stu!

From conversations I've had with @jonathanstowell over the last year, I still believe there are portions of the code that have never been run.  Given the fixes to the "first cut" we've had to make to the parts that now *are* working, I think it would be foolish to announce it as complete (i.e. take off the suffix).

Obviously you're free to use the Alpha version if that helps.  There is also the "other" client - https://github.com/Speedygeek/ZendeskApi_v2, which has twice as many downloads as the this client.

We've had various discussions on getting some automated tests going for this client over the last year but so far nothing has come of it.

**Comment by slang25** [comment]
Thanks for the response @gareththackeray 😃 

That makes sense, I guess it being pre-release is an honest representation of the real world testing that it's undergone.

fwiw I've looked at that other package, and implementation wise I prefer this library. No disrespect intended to the contributors there.

**Pull request closed without merging**
